### ISSUE TITLE
[BUG] Latest patch of rickshaw has disrupted the test cycle

### ISSUE THREAD

**Issue by pradiptapks** [perftool-incubator/rickshaw#433]
Following the recent update, the latest patch applied to Crucible has disrupted the test cycle during processing stage 10. Upon investigation, it has come to my attention that the latest patch is associated with the Rickshaw project. 

http://storage.scalelab.redhat.com/psahoo/PerfTaskLog/debuging/trafficgen--2023-12-01_06%3A24%3A44_UTC--f103c4c2-1e4b-4552-85f3-4a8f057ae48c.tar.xz

```
[2023-12-01 06:24:58.553][STDOUT] Processing stage 10 (663d4283c7c9306d92f0b557a7dc8a04_x86_64)...
[2023-12-01 06:26:12.605][STDOUT] Workshop build failed: rc=30
[2023-12-01 06:26:12.605][STDOUT] Workshop build command: /opt/crucible/subprojects/core/workshop/workshop.pl --log-level verbose  --config /var/lib/crucible/run/trafficgen--2023-12-01_06:24:44_UTC--f103c4c2-1e4b-4552-85f3-4a8f057ae48c/config/cs-conf.json --param %bench-dir%=/opt/crucible/subprojects/benchmarks/trafficgen --param %engine-dir%=/opt/crucible/repos/https:github.com:perftool-incubator/rickshaw/engine/ --param %rickshaw-dir%=/opt/crucible/repos/https:github.com:perftool-incubator/rickshaw --reg-tls-verify=true 2>&1 --skip-update true  --userenv /var/lib/crucible/run/trafficgen--2023-12-01_06:24:44_UTC--f103c4c2-1e4b-4552-85f3-4a8f057ae48c/config/userenv-d0154fa893c8960e4c726362bbb9e9f0_x86_64.json --requirement /opt/crucible/subprojects/benchmarks/trafficgen/workshop.json --proj quay.io/crucible --label client-server --tag 663d4283c7c9306d92f0b557a7dc8a04_x86_64
[2023-12-01 06:26:12.605][STDOUT] Workshop build output:
...
[2023-12-01 06:26:12.651][STDOUT] [ERROR] /usr/bin/pip3
[2023-12-01 06:26:12.651][STDOUT] [ERROR] WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
[2023-12-01 06:26:12.651][STDOUT] [ERROR] Collecting pyyaml
[2023-12-01 06:26:12.651][STDOUT] [ERROR]   Cache entry deserialization failed, entry ignored
[2023-12-01 06:26:12.651][STDOUT] [ERROR]   Downloading https://files.pythonhosted.org/packages/cd/e5/af35f7ea75cf72f2cd079c95ee16797de7cd71f29ea7c68ae5ce7be1eda0/PyYAML-6.0.1.tar.gz (125kB)
[2023-12-01 06:26:12.651][STDOUT] [ERROR] Exception:
[2023-12-01 06:26:12.652][STDOUT] [ERROR] Traceback (most recent call last):
[2023-12-01 06:26:12.652][STDOUT] [ERROR]   File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 565, in untar_file
[2023-12-01 06:26:12.652][STDOUT] [ERROR]     tarfile.data_filter(member.replace(name=fn), location)
[2023-12-01 06:26:12.652][STDOUT] [ERROR] AttributeError: module 'tarfile' has no attribute 'data_filter'
[2023-12-01 06:26:12.652][STDOUT] [ERROR] 
[2023-12-01 06:26:12.652][STDOUT] [ERROR] During handling of the above exception, another exception occurred:
[2023-12-01 06:26:12.652][STDOUT] [ERROR] 
[2023-12-01 06:26:12.652][STDOUT] [ERROR] Traceback (most recent call last):
[2023-12-01 06:26:12.652][STDOUT] [ERROR]   File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
[2023-12-01 06:26:12.652][STDOUT] [ERROR]     status = self.run(options, args)
[2023-12-01 06:26:12.652][STDOUT] [ERROR]   File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 346, in run
[2023-12-01 06:26:12.652][STDOUT] [ERROR]     requirement_set.prepare_files(finder)
[2023-12-01 06:26:12.652][STDOUT] [ERROR]   File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 381, in prepare_files
[2023-12-01 06:26:12.652][STDOUT] [ERROR]     ignore_dependencies=self.ignore_dependencies))
[2023-12-01 06:26:12.652][STDOUT] [ERROR]   File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 623, in _prepare_file
[2023-12-01 06:26:12.652][STDOUT] [ERROR]     session=self.session, hashes=hashes)
[2023-12-01 06:26:12.652][STDOUT] [ERROR]   File "/usr/lib/python3.6/site-packages/pip/download.py", line 822, in unpack_url
[2023-12-01 06:26:12.652][STDOUT] [ERROR]     hashes=hashes
[2023-12-01 06:26:12.652][STDOUT] [ERROR]   File "/usr/lib/python3.6/site-packages/pip/download.py", line 664, in unpack_http_url
[2023-12-01 06:26:12.652][STDOUT] [ERROR]     unpack_file(from_path, location, content_type, link)
[2023-12-01 06:26:12.883][STDOUT] [ERROR]   File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 622, in unpack_file
[2023-12-01 06:26:12.883][STDOUT] [ERROR]     untar_file(filename, location)
[2023-12-01 06:26:12.883][STDOUT] [ERROR]   File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 566, in untar_file
[2023-12-01 06:26:12.883][STDOUT] [ERROR]     except tarfile.LinkOutsideDestinationError:
[2023-12-01 06:26:12.883][STDOUT] [ERROR] AttributeError: module 'tarfile' has no attribute 'LinkOutsideDestinationError'
[2023-12-01 06:26:12.883][STDOUT] [ERROR] 
[2023-12-01 06:26:12.883][STDOUT] [ERROR] ********************************************************************************
[2023-12-01 06:26:12.883][STDOUT] [ERROR] Failed to run command 'if command -v pip3; then pip3 install pyyaml; else echo 'pip3 not found'; fi'
[2023-12-01 06:26:12.883][STDOUT] [VERBOSE] Performing async/coro enter
[2023-12-01 06:26:12.883][STDOUT] [VERBOSE] Performing async/coro leave
[2023-12-01 06:26:12.883][STDOUT] Skipping run post-processing due to error(s) [rc=1]
[2023-12-01 06:26:13.884][STDOUT] Archiving crucible log to /var/lib/crucible/run/trafficgen--2023-12-01_06:24:44_UTC--f103c4c2-1e4b-4552-85f3-4a8f057ae48c/crucible.log.xz
```

**Comment by k-rister** [comment]
I think this is already resolved.
